name: Build and Deploy

on:
  push:
    branches:
      - master
      - main # atau main, sesuaikan dengan nama branch kamu intinya terserah kamu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Plugins
        run: ./gradlew make

      - name: Push to Builds
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b builds
          git add .
          git commit -m "Update builds"
          git push -f origin builds
